robot_base_frame: chassis
transform_tolerance: 0.2
obstacle_range: 2.5

# set footprint based on collision of the robot with padding
footprint: [[0.0,-0.073],[0.215,-0.073],[0.215,0.073],[0.0,0.073]]
footprint_padding: 0.02

# parameter for inflation layer
inflation_layer:
  inflation_radius: 0.5
  cost_scaling_factor: 5.0

# parameter for obstacle layer
obstacle_layer:
  observation_sources: lidar_scan
  lidar_scan: 
    topic: mbrb/lidar/scan

    # since frequency from lidar is 12 HZ -> 0.083
    expected_update_rate: 0.1
    data_type: LaserScan
    marking: true
    clearing: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.08
  