global_costmap:
  global_frame: map

  update_frequency: 5.0
  publish_frequency: 3.0

  # load static map and set rolling window to false
  static_map: true
  rolling_window: false

  plugins: 
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
