
local_costmap:
  global_frame: map

  update_frequency: 10.0
  publish_frequency: 3.0
  
  # using rolling window for local costmap
  static_map: false
  rolling_window: true

  width: 3
  height: 3
  resolution: 0.025
  
  # parameter for inflation layer
  inflation_layer:
    inflation_radius: 0.3
    # cost_scaling_factor: 5.0

  plugins: 
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
