# using TrajectoryPlannerROS as a wrapper
TrajectoryPlannerROS:

# robot configuration paramter
  # set acceleration limits
  acc_lim_x: 2.0
  acc_lim_y: 2.0
  acc_lim_theta: 3.2 

  # set velocity limits
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.7

  min_in_place_vel_theta: 0.4
  escape_vel: -0.1
  
  # since this is differential drive robot, this paramter must be set to false
  holonomic_robot: false

# goal tolerance paramter
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05

# forward simulation paramter
  sim_time: 1.0
  sim_granularity: 0.025

  vx_samples: 3
  vtheta_samples: 20
  controller_frequency: 30

# trajectory scoring parameter
  pdist_scale: 0.4
  gdist_scale: 0.4
  occdist_scale: 0.5

  heading_lookahead: 1.5
  dwa: true
  global_frame_id: odom

  oscillation_reset_dist: 0.05

  prune_plan: true