
local_costmap:
  global_frame: odom

  update_frequency: 10.0
  publish_frequency: 3.0
  
  # using rolling window for local costmap
  static_map: false
  rolling_window: true

  width: 3
  height: 3
  resolution: 0.025

  plugins: 
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
