mbrb:
  joint_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  left_wheel_v_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 1, i: 3, d: 0.01}
  right_wheel_v_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 1, i: 3, d: 0.01}